### ISSUE TITLE
Value of `type` concept field is inconsistent

### ISSUE THREAD

**Issue by strogonoff** [geolexica/osgeo-glossary#2]
This concept has `type`: https://github.com/geolexica/osgeo-glossary/blob/e2b4e932d4e6c36466235498c3aad232c4265664/concepts/concept-32.yaml#L1-L14

This concept doesn’t have `type`: https://github.com/geolexica/osgeo-glossary/blob/862c7373d956d51d096c53f76c2f03117e0421e6/concepts/concept-105.yaml#L1-L11

Method definition: https://github.com/geolexica/osgeo-termbase/blob/565819ab9c2ba4408cc442f623a6a3c1039102a5/lib/osgeo/termbase/term.rb#L172-L177

**Comment by strogonoff** [comment]
cc’ing @ronaldtse though I guess it’s just a symptom of early stage data gathering

**Comment by ronaldtse** [comment]
Indeed, this is due to early data gathering. Concept 105 is `type: abbrev` because it's an abbreviation.

**Comment by skalee** [comment]
I suppose this is outdated and we should close it. Objections, @strogonoff, @ronaldtse?

Grepping with `grep -e 'type:' -r osgeo-glossary/concepts --no-filename | uniq` gives only: `type: expression`.

----

Abbreviations are handled in a different way now (`abbrev: true`), full example below. If this is incorrect for Glossarist, please say a word @strogonoff.

```
term: 3-D Elevation Program
termid: 1
eng:
  id: 1
  language_code: eng
  notes: []
  examples: []
  authoritative_source:
    link: https://www.osgeo.org/initiatives/geo-for-all/geo-newsletters-archive/
  terms:
  - type: expression
    designation: 3-D Elevation Program
    normative_status: preferred
  - type: expression
    designation: 3DEP
    normative_status: preferred
    abbrev: true
```
