### ISSUE TITLE
Provide a simple register.yaml

### ISSUE THREAD

**Issue by strogonoff** [geolexica/osgeo-glossary#6]
See [example](https://github.com/geolexica/isotc211-glossary/blob/master/register.yaml).

@ronaldtse, could you give a pointer where relevant information could be found?

**Comment by ronaldtse** [comment]
```yaml
name: OSGeo Lexicon

description: >-
  The OSGeo Lexicon is the online glossary for OSGeo, managed by the OSGeo Lexicon Committee.
```

Would this work?

**Comment by strogonoff** [comment]
@ronaldtse, it needs at least one subregister for language-specific data. Is there only English?

**Comment by strogonoff** [comment]
Then that would be (subregister data empty as it supposed to be)

```yaml
name: OSGeo Lexicon

description: >-
  The OSGeo Lexicon is the online glossary for OSGeo, managed by the OSGeo Lexicon Committee.

subregisters:
  eng:
```
